title: "Galilea Cabrales"
description: "¡Hola! Te doy la bienvenida a mi portafolio de proyectos de Análisis de Datos."
theme: jekyll-theme-minimal
url: "https://galileacabrales.github.io"
author: "Galilea Cabrales"
